#! /bin/bash
JAR_PATH=/usr/lib/uc-pircbotx/uc_pircbotx.jar
MAIN_CLASS=uk.co.unitycoders.pircbotx.BotService
CONF_DIR=/etc/uc_pircbotx.json
EXTRAS_DIR=/usr/lib/uc-pircbotx/extras/*
DEP_PATHS="/usr/share/java/guava.jar:/usr/share/java/gson.jar:/usr/share/java/commons-daemon.jar:/usr/share/java/slf4j-api.jar:/usr/share/java/slf4j-simple.jar:/usr/lib/uc-pircbotx/deps/*"

# Set useful variables
CLASSPATH="$CLASSPATH:$DEP_PATHS:$JAR_PATH:$EXTRAS_DIR"
echo $CLASSPATH

# Check the config file exists
if [ ! -f $CONF_FILE ];
then
	echo "config file missing (wrong directory or run unix-config)"
	exit 1
fi

/usr/bin/jsvc -jvm server $@ -cwd `pwd` -cp $CLASSPATH $MAIN_CLASS
